### ISSUE TITLE
Doesn't work under Win10 21H2 (Build 19044.1586)

### ISSUE THREAD

**Issue by Eagle3386** [zhufucdev/EdgeRemover#2]
Copied from my original report over at da2x/EdgeDeflector#141:

@zhufucdev Doesn't work here - steps to reproduce:
1. Downloaded `EdgeRemover.exe` from your repo's releases tab (tagged as `polished`).
2. Put the application next to EdgeDeflector (`C:\Users\[MyUserName]\AppData\Local\Programs\EdgeDeflector`).
3. Opened PowerShell (as admin), "`cd`'ed" into aforementioned directory & ran `.\EdgeRemover.exe`.
4. Got the "success message box":
![image](https://user-images.githubusercontent.com/5111490/158966411-9ba62688-c7c2-4f0d-b854-bf1330bc96dd.png)
5. Confirmed that the registry's value is set correctly:
![image](https://user-images.githubusercontent.com/5111490/158966744-e73d66f5-7b1f-4caa-b33f-dfa086d8e1d8.png)
6. Went into settings, default apps by protocol, only to see 2 selectable Edge entries:
![image](https://user-images.githubusercontent.com/5111490/158967253-499e6122-af00-4d8a-8909-cf049454ee07.png)
7. Even set all Edge-related items back to the entry with Edge's icon.

Yet, the result is always the same: no Edge or any other browser (-tab) is launched - neither from taskbar's news flyout, nor EdgeDeflector's "test link", `microsoft-edge:https://www.ctrl.blog`, nor any other Edge-forced link I could find & try.

Any help would be greatly appreciated...

In addition, the `edge-remover.lock` exists at the aforementioned folder & its content is: `2022-03-18 10:16:33`.

**Comment by zhufucdev** [comment]
What this app does:
1. Modify registration so that every time msedge.exe is supposed to be called, this app is called instead.
2. Parse the parameter it receives to get the direct URL, and use system's method to open it.
3. If the system prefers to open it with Edge again, which is redirect to the app, it exits because msedge.exe is not available logically anymore.

The third step is completed by comparing the content of `edge-remover.lock` with system time. If the time span is within 1 second, the origin operation is considered unavailable.

Your problem may lay in:
* The default browser is set to msedge.exe
* The comparison didn't complete with 1s
* Or more complicatedly, the protocol is very different from what it is on my testing environment.

**Comment by Eagle3386** [comment]
> What this app does:
> (...) 
> 2. Parse the parameter it receives to get the direct URL, and use system's method to open it.

This might need improvement.

> 3. If the system prefers to open it with Edge again, which is redirect to the app, it exits because msedge.exe is not available logically anymore.

I don't fully understand what you mean by saying this.

> The third step is completed by comparing the content of `edge-remover.lock` with system time. If the time span is within 1 second, the origin operation is considered unavailable.

Why is that?
 
> Your problem may lay in:
>     * The default browser is set to msedge.exe

Nope, it's set to Firefox Dev Edition.

>     * The comparison didn't complete with 1s

Probably unrealistic as I'm on a Ryzen 7 5800U with 32 GB RAM & not any heavy workload at all.

>     * Or more complicatedly, the protocol is very different from what it is on my testing environment.

Might be true, so even easier repo steps:
1. Press <kbd>Win</kbd> + <kbd>R</kbd>.
2. Enter `microsoft-edge:https://www.example.net/` & hit <kbd>Enter</kbd>.
3. I expect Firefox to open `https://www.example.net/`, but nothing happens.
4. Running [Process Hacker](https://github.com/processhacker/processhacker) (Nightly build, i. e. version 3.0.x, but 2.39 should be sufficient, too), I used its process filter (upper right textbox or <kbd>CTRL</kbd> + <kbd>K</kbd>) to filter for `edge`, but neither `msedge.exe` nor `EdgeRemover.exe` show up for even a brief moment while testing your program.

**Comment by Eagle3386** [comment]
Update: set Edge-stuff to Edge (the one _with_ the icon in my OP's image) & tried `microsoft-edge:https://www.example.net/` again:
![image](https://user-images.githubusercontent.com/5111490/158984444-e7e9822a-790c-4d45-98bc-9dec3bc29a74.png)

Using Process Hacker, I got the full command line:
`C:\Users\[MyUserName]\AppData\Local\Programs\EdgeDeflector\EdgeRemover.exe "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --single-argument microsoft-edge:https://www.example.net/`

How to redirect this call to Firefox instead of showing the error message box & simply stop processing the web request? EdgeDeflector won't work as reported by several users over at its repo..

**Comment by zhufucdev** [comment]
> Update: set Edge-stuff to Edge (the one _with_ the icon in my OP's image) & tried `microsoft-edge:https://www.example.net/` again: ![image](https://user-images.githubusercontent.com/5111490/158984444-e7e9822a-790c-4d45-98bc-9dec3bc29a74.png)
> 
> Using Process Hacker, I got the full command line: `C:\Users\[MyUserName]\AppData\Local\Programs\EdgeDeflector\EdgeRemover.exe "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --single-argument microsoft-edge:https://www.example.net/`
> 
> How to redirect this call to Firefox instead of showing the error message box & simply stop processing the web request? EdgeDeflector won't work as reported by several users over at its repo..

That's exactly what I meant to tell you to do by mentioning
> Your problem may lay in:
> * The default browser is set to msedge.exe

Sorry for my unthoughtful expression
Just try any edge-forced link on the information flow panel

**Comment by Eagle3386** [comment]
> That's exactly what I meant to tell you to do by mentioning

Glad we figured it out & "found" each other's intention. ;)

> Sorry for my unthoughtful expression Just try any edge-forced link on the information flow panel

All good, except: now that we found such an Edge-forced link (`microsoft-edge:https://www.example.net/`), how to tell Windows to open it in Firefox (or any other browser that is set as "Default browser")?

**Comment by zhufucdev** [comment]
I have to admit that the app has its limitation. Among my tests, there's no case where links of such pattern is used, neither did I know about it, so I didn't design the program this way.
If there is practical case where links of this pattern should be considered, I'll implement it in the next release.

**Comment by Eagle3386** [comment]
Sad that you closed the issue right away - but for anyone interested, there's a _working_ alternative here on GitHub, available over at [rcmaehl/MSEdgeRedirect](https://github.com/rcmaehl/MSEdgeRedirect).
Using it's `Active Mode`, Edge isn't even launched prior to redirection, i. e. it works just as EdgeDeflector did previously. 🥳

Bonus: it does de-bloating of Bing searches, MSN news, MSN weather, Edge-forced PDF, etc.

**Comment by k2helix** [comment]
> I have to admit that the app has its limitation. Among my tests, there's no case where links of such pattern is used, neither did I know about it, so I didn't design the program this way. If there is practical case where links of this pattern should be considered, I'll implement it in the next release.

Just installed EdgeRemover along EdgeDeflector and there is such case where this error dialog opens. Latest Windows 11 22H2, by clicking the new Bing chat icon on the task bar. 

![imagen](https://github.com/zhufucdev/EdgeRemover/assets/49949593/b032602f-b09b-4eaf-91da-1ac30983ad0f)

Didn't install MSEdgeRedirect as its background process consumes some of my CPU

**Comment by Eagle3386** [comment]
@k2helix There are 2 modes for installation of MSEdgeRedirect - just try the other one. 😉
Besides, some CPU usage is pretty normal, because it has to check links for either "catching" or passing them…

**Comment by k2helix** [comment]
Oh right I didn't see it because I installed it with winget :sweat_smile:
