### ISSUE TITLE
Documentation is needed to go back to original behavior

### ISSUE THREAD

**Issue by jooyoungseo** [zhufucdev/EdgeRemover#3]
I was wondering if there would be any way to go back to original behavior after applying `EdgeRemover`. It would be even better if the uninstaller was provided or if the instruction was provided.

**Comment by hooddy** [comment]
Just remove those registry entry. And delete edgeremove executable file.

**Comment by zhufucdev** [comment]
the entry is at `Computer\HKEY_LOCAL_MACHINESOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe`

should be ok to remove the whole section via registry editor in the tree view on the left
